name: isolate_cluster
version: 0.17.2
description: A library to build up a cluster of isolates. In a cluster an isolate can spawn or lookup other isolates and send messages to other isolates.
author: Oliver Damm <oliver.damm@gmx.de>
homepage: https://www.github.com/blimster/isolate_cluster

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  uuid: ^2.0.0
  logging: ^0.11.3

dev_dependencies:
  test: ^1.6.2
