name: isolate_cluster
version: 0.15.0
description: A library to build up a cluster of isolates.
author: Oliver Damm <oliver.damm@gmx.de>
homepage: http://www.github.com/blimster/isolate_cluster
environment:
  sdk: ">=1.21.1 <2.0.0"
dependencies:
  uuid: "^0.5.0"
  logging: "^0.11.2"
dev_dependencies:
  test: "^0.12.6+2"
