name: isolate_cluster
version: 0.16.2
description: A library to build up a cluster of isolates.
author: Oliver Damm <oliver.damm@gmx.de>
homepage: http://www.github.com/blimster/isolate_cluster

environment:
  sdk: '>=2.0.0-dev.68.0 <2.0.0'

dependencies:
  uuid: ^1.0.1
  logging: ^0.11.3

dev_dependencies:
  test: ^1.3.0
